# Generated by Django 4.2.23 on 2025-07-21 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_checkup_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Как вас зовут?', max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(help_text='Ваш номер телефона', max_length=20, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, help_text='Электронная почта (необязательно)', max_length=254, null=True, verbose_name='Email')),
                ('message', models.TextField(blank=True, help_text='Дополнительная информация или вопросы', null=True, verbose_name='Сообщение')),
                ('source_page', models.CharField(choices=[('stocks_page', 'Страница акций'), ('services_page', 'Страница услуг'), ('main_page', 'Главная страница'), ('specialists_page', 'Страница специалистов'), ('checkup_page', 'Страница чекапа'), ('other', 'Другое')], default='other', help_text='С какой страницы была отправлена заявка', max_length=20, verbose_name='Источник заявки')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В обработке'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='new', max_length=20, verbose_name='Статус заявки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP адрес пользователя', null=True, verbose_name='IP адрес')),
                ('user_agent', models.TextField(blank=True, help_text='Информация о браузере пользователя', null=True, verbose_name='User Agent')),
                ('related_checkup', models.ForeignKey(blank=True, help_text='Чекап, по которому была отправлена заявка', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.checkup', verbose_name='Связанный чекап')),
                ('related_doctor', models.ForeignKey(blank=True, help_text='Врач, к которому хотят записаться', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.doctor', verbose_name='Связанный врач')),
                ('related_service', models.ForeignKey(blank=True, help_text='Услуга, по которой была отправлена заявка', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.service', verbose_name='Связанная услуга')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='products_co_created_610c62_idx'), models.Index(fields=['status'], name='products_co_status_d0b731_idx'), models.Index(fields=['phone'], name='products_co_phone_f77b93_idx')],
            },
        ),
    ]
