# Generated by Django 4.2.23 on 2025-07-24 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_contactrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, help_text='Фотография врача', null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='online_booking_link',
            field=models.URLField(blank=True, help_text='Ссылка на онлайн-запись к врачу', max_length=500, null=True),
        ),
    ]
