# Generated by Django 4.2.23 on 2025-07-24 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_doctor_image_doctor_online_booking_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrequest',
            name='source_page',
            field=models.CharField(choices=[('stocks_page', 'Страница акций'), ('services_page', 'Страница услуг'), ('main_page', 'Главная страница'), ('specialists_page', 'Страница специалистов'), ('checkup_page', 'Страница чекапа'), ('doctor_profile_page', 'Страница профиля врача'), ('other', 'Другое')], default='other', help_text='С какой страницы была отправлена заявка', max_length=20, verbose_name='Источник заявки'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, help_text='Фотография врача', null=True, upload_to='doctors/'),
        ),
    ]
